services:
  - type: web
    name: palete-studio
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PHOTOROOM_API_KEY
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
        sync: false
      - key: SUPABASE_URL
        value: your_supabase_project_url_here
      - key: SUPABASE_SERVICE_KEY
        sync: false
